### ISSUE TITLE
Api burn nft does not work

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#72] opened 2022-11-08 03:23 UTC
Recently, i have used api:
 await client.burnNonFungibleToken('ee3955c8', '10000001', '00000002', {
    ownerAddress: "",
    ownerSecret: "",
    fromUserId: 'U8853f82b832513d479fb634ef7d1eee3'
  })
  but when i check in [line blockchain](https://explorer.blockchain.line.me/cashew) it return failed, and nft was not burn.
  
![image](https://user-images.githubusercontent.com/108503412/200467750-794be078-0f03-4149-92f6-162e51ff2ec3.png)
So i decided to check with api:
  const res = await client.transactionResult(
    "2CD7BDC53FD9CEF3CCDFDDBC0E110ECCE0396F9CC9A177A374F1075E8A3A456E"
  );
![image](https://user-images.githubusercontent.com/108503412/200467581-aef16c55-336c-46e7-9be4-1c19bcfdd889.png)

It returns success but logs is empty. Please check this issue. Thank you so much.

**Comment by ryukato** [comment] 2022-11-09 06:50
I guess it look the user didn't approve proxy, which means the proxy account(address) is not authorized as proxy. so I appreciate if you check the proxy is set on the item-token-collection(contract - ee3955c8) by below API, and the proxy address is correct one that has proxy authority.
* [Retrieve whether the item token proxy set or not
](https://docs-blockchain.line.biz/api-guide/category-users/retrieve#v1-users-userId-item-tokens-contractId-proxy-get)

**Comment by ducnh-wano** [comment] 2022-11-10 09:05
i've tried this:
![image](https://user-images.githubusercontent.com/108503412/201046797-e9b63b56-e79d-4692-a793-47824f5ad831.png)
so response returns
![image](https://user-images.githubusercontent.com/108503412/201046877-af9e2214-d71e-4ca4-bb4a-4a0a477f5d6d.png)
How can i fix this.
So let me describe the things that my company want me to do that is when i create a nft, i have to set a time like 01/01/2023 so up to that time (01/01/2023) trigger a cronjob to delete all infomation of that nft. People who bought this also loss their nft. I know that sound a bad thing.

**Comment by ryukato** [comment] 2022-11-21 01:52
Sorry for late response, but I think it's hard to set a proxy right after an item token collection(contract) because it needs several steps and some of steps are required a user' action(approval) through wallet system.
More details, (* **Below steps has to be done after an item token collection(contract) has been created**)
1. if you send a proxy request to chain via open-api
2. LBW(wallet system, LINE Blockchain Wallet), sends a notification to get the user's approval for the proxy setting, which is approve a service wallet to mint, burn and transfer.
3. when the user approves the proxy request, then there will be a transaction for approval of the proxy request.
4. The transaction has been confirmed, then open-api sends callback for the transaction, and proxy setting is checked by [v1-users-userId-item-tokens-contractId-proxy-get](https://docs-blockchain.line.biz/api-guide/category-users/retrieve#v1-users-userId-item-tokens-contractId-proxy-get) API.

I am not sure what exactly you want to do, but you'd better understand how proxy request and approval are working.
And it does not look a bug, it could be caused by already existing proxy request on same user or the steps are not completed. I appreciate if you check any previous requests are and log or save what your system request to LBD

**Comment by ryukato** [comment] 2022-11-21 02:55
[FYI Setup proxy]
* https://docs-blockchain-beta.line-beta.biz/sample-services/Link-cinema#3-set-up-the-proxy

I hope the document can help you.

**Comment by ryukato** [comment] 2022-12-16 06:21
I will close this issue because there has been no additional comments.

**Closed as completed by ryukato** 2022-12-16 06:21 UTC
